### ISSUE TITLE
Does this fork work? 

### ISSUE THREAD

**Issue by LucianoGanga** [wiggin/express-restify-mongoose#3]
Hi! I'd like to know if you could make this fork work, as when I'm installing it, it doesn't work  and I don't know if I'm doing something wrong or the fork isn't finished yet. 

Thanks!
Luciano

**Comment by pixel2** [comment]
Hi, everything in this fork should have been merged with master at https://github.com/florianholzapfel/express-restify-mongoose so I recommend using that one instead.

**Comment by LucianoGanga** [comment]
Hello @pixel2 ! 
As this wasn't adapted to work with KOA and I needed it, I ended making my own fork with a working version. If you need it, you can access it through this links: 

GitHub: https://github.com/LucianoGanga/koa-restify-mongoose
NPM: https://www.npmjs.com/package/koa-restify-mongoose

Thanks!
Luciano
